language: php

env:
  - NETTE=default
  - NETTE=~2.2.0

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - php .travis.composer.php
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - composer create-project --prefer-source --dev --no-interaction jakub-onderka/php-parallel-lint parallel-lint ~0.8.0
  - composer create-project --prefer-source --dev --no-interaction nette/code-checker code-checker ~2.2.0

script:
    - php parallel-lint/parallel-lint.php -e php,phpt src tests
    - php code-checker/src/code-checker.php -d src
    - php code-checker/src/code-checker.php -d tests
    - vendor/bin/tester -s -p php tests
